version: "3"
services:
  web:
    environment:
      - HTTP_HOST=0.0.0.0
      - HTTP_PORT=8080
      - LOG_LEVEL=info
    build:
      context: .
      args:
        - HYPERFIDDLE_ELECTRIC_APP_VERSION
    ports:
      - '8080:8080'
