# fly.toml app configuration file generated for casa on 2023-09-17T16:29:49+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "casa"
primary_region = "sin"

[build]

[env]
  HTTP_HOST = "0.0.0.0"
  HTTP_PORT = "8080"
  LOG_LEVEL = "info"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 0
  processes = ["app"]
