name: Fly Deploy
on:
  push:
    branches:
      - main
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}      
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            /usr/src/app/.m2/repository
            /usr/src/app/node_modules
          key: cljdeps-${{ hashFiles('project.clj') }}
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            cljdeps-
            npm-
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --build-arg HYPERFIDDLE_ELECTRIC_APP_VERSION=$(git describe --tags --long --always --dirty)
      - run: flyctl scale memory 512
