name: Fly Deploy
on:
  push:
    branches:
      - main
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}      
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache Maven Artifacts
        uses: actions/cache@v3
        with:
          path: /usr/src/app/.m2/repository
          key: cljdeps-${{ hashFiles('project.clj') }}
          restore-keys: cljdeps-
      - name: Cache Node Modules          
        uses: actions/cache@v3
        with:
          path: /usr/src/app/node_modules
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy to Fly.io
        run: LOG_LEVEL=DEBUG flyctl deploy --build-arg HYPERFIDDLE_ELECTRIC_APP_VERSION=$(git describe --tags --long --always --dirty) --remote-only
      - name: Scale RAM to 512MB        
        run: flyctl scale memory 512
